name: Block Workflow Modifications

on:
  workflow_call:
    inputs:
      ALLOWED_USERS:
        description: 'Comma-separated list of GitHub users that are allowed to modify workflow files.'
        type: string
        required: false

jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    outputs:
      ALLOWED_USERS: ${{ steps.validate-users.outputs.ALLOWED_USERS }}

    steps:
      - name: Validate and set ALLOWED_USERS
        id: validate-users
        env:
          ALLOWED_USERS: ${{ inputs.ALLOWED_USERS }}
        run: |
          if [[ -z "$ALLOWED_USERS" ]]; then
            echo "No specific users allowed. All users will be checked against the organization."
            echo "ALLOWED_USERS=" >> $GITHUB_OUTPUT
          else
            echo "Using allowed users: $ALLOWED_USERS"
            echo "ALLOWED_USERS=$ALLOWED_USERS" >> $GITHUB_OUTPUT
          fi  

  block:
    needs: validate-inputs
    runs-on: ubuntu-latest
    outputs:
      should_close: ${{ steps.check-user.outputs.should_close }}
    steps:
      - name: Check if GITHUB_ACTOR is allowed
        id: check-user
        run: |
          ALLOWED_USERS_LIST="${{ needs.validate-inputs.outputs.ALLOWED_USERS }}"
          IFS=',' read -ra ALLOWED_USERS <<< "$ALLOWED_USERS_LIST"

          echo "should_close=true" >> $GITHUB_OUTPUT

          for user in "${ALLOWED_USERS[@]}"; do
            if [[ "$GITHUB_ACTOR" == "$user" ]]; then
              echo "User $GITHUB_ACTOR is allowed to modify workflow files."
              echo "should_close=false" >> $GITHUB_OUTPUT
            fi
          done
          

  close-pr:
    needs: block
    if: needs.block.outputs.should_close == 'true'
    uses: crickets-and-comb/shared/.github/workflows/close_pr.yml@main
    with:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_AUTHOR: ${{ github.actor }}
      REASON: "Workflow file modifications are restricted. Please contact a repository administrator if this is an error."