name: Dispatch Restrict External PRs

on:
  pull_request:
    types: [opened]

jobs:
  close-external-prs:
    uses: ./.github/workflows/block_outside_PRs.yml
    with:
      ALLOWED_ORG: "crickets-and-comb"
    secrets:
      ORG_READ_TOKEN: ${{ secrets.ORG_READ_TOKEN }}