name: Restrict External PRs

on:
  workflow_call:
    inputs:
      ALLOWED_ORG:
        description: 'GitHub organization name that is allowed to open PRs.'
        type: string
        required: false
        default: ""
      ALLOWED_USERS:
        description: 'Comma-separated list of GitHub users who are allowed to open PRs even if they are not in the organization.'
        type: string
        required: false
    secrets:
      ORG_READ_TOKEN:
        required: true

defaults:
  run:
    shell: bash -el {0}

jobs:
  close-external-prs:
    runs-on: ubuntu-latest
    outputs:
      should_close: ${{ steps.check-permission.outputs.should_close }}
    steps:
      - name: Check PR Author and Close If External
        id: check-permission
        run: |
          set -e

          should_close=true
          echo "should_close=$should_close" >> $GITHUB_OUTPUT # For good measure.

          prAuthor=$(jq -r '.pull_request.user.login' < "$GITHUB_EVENT_PATH")
          allowedOrg=${{ inputs.ALLOWED_ORG }}
          prNumber=$(jq -r '.pull_request.number' < "$GITHUB_EVENT_PATH")

          IFS=',' read -ra ALLOWED_USERS <<< "${{ inputs.ALLOWED_USERS }}"
          for user in "${ALLOWED_USERS[@]}"; do
            if [[ "$prAuthor" == "$user" ]]; then
              echo "User $prAuthor is explicitly allowed. PR remains open."
              should_close=false
            fi
          done

          if [[ $should_close == 'true' && -n "$allowedOrg" ]]; then
            {
              echo "Checking if user $prAuthor is a member of $allowedOrg..."
              response=$(curl -s -S -H "Authorization: Bearer ${{ secrets.ORG_READ_TOKEN }}" \
                                -H "Accept: application/vnd.github.v3+json" \
                                https://api.github.com/orgs/$allowedOrg/memberships/$prAuthor)

              state=$(echo "$response" | jq -r '.state // empty')
              if [[ "$state" == "active" ]]; then
                echo "User $prAuthor is a member of $allowedOrg. PR remains open."
                should_close=false
              else
                echo "User $prAuthor is not a member of $allowedOrg. Closing PR."
                echo "Response: $response"
                should_close=true
              fi
            } || {
              echo "An error occurred during membership validation. Closing PR as a precaution."
              should_close=true
            }
          fi
          echo "Final decision: should_close=$should_close"
          echo "should_close=$should_close" >> $GITHUB_OUTPUT

  close-pr:
    needs: close-external-prs
    if: needs.close-external-prs.outputs.should_close == 'true'
    uses: crickets-and-comb/shared/.github/workflows/close_pr.yml@main
    with:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_AUTHOR: ${{ github.actor }}
      REASON: "Only members of ${{ inputs.ALLOWED_ORG }} or explicitly allowed users can open pull requests. Please file an issue for discussion if needed."