name: Release to GitHub

on:
  workflow_call:
    inputs:
      DIST_DIR:
        description: 'Directory to store dist files. Typically `dist/`.'
        type: string
        required: true
      PYTHON_BUILD_VERSION:
        description: 'Python version to use for misc tasks.'
        type: string
        required: true
      PYTHON_PACKAGE_DIST_NAME:
        description: 'Name of the dist artifact to upload. Acts like a key.'
        type: string
        required: true
    secrets:
      CHECKOUT_SHARED:
        required: true

defaults:
  run:
    shell: bash -el {0}

jobs:
  validate-inputs:
    name: Validate Inputs
    runs-on: ubuntu-latest
    outputs:
      DIST_DIR: ${{ steps.validate-dist-dir.outputs.DIST_DIR }}
      PYTHON_BUILD_VERSION: ${{ steps.validate-python-version.outputs.PYTHON_BUILD_VERSION }}
      PYTHON_PACKAGE_DIST_NAME: ${{ steps.validate-package-name.outputs.PYTHON_PACKAGE_DIST_NAME }}

    steps:
      - name: Validate and set DIST_DIR
        id: validate-dist-dir
        env:
          DIST_DIR: ${{ inputs.DIST_DIR }}
        run: |
          if [[ -z "$DIST_DIR" ]]; then
            echo "DIST_DIR is required."
            exit 1
          fi

          echo "Using DIST_DIR: $DIST_DIR"
          echo "DIST_DIR=$DIST_DIR" >> $GITHUB_OUTPUT

      - name: Validate and set PYTHON_BUILD_VERSION
        id: validate-python-version
        env:
          PYTHON_BUILD_VERSION: ${{ inputs.PYTHON_BUILD_VERSION }}
        run: |
          if [[ -z "$PYTHON_BUILD_VERSION" ]]; then
            echo "PYTHON_BUILD_VERSION is required."
            exit 1
          fi

          echo "Using PYTHON_BUILD_VERSION: $PYTHON_BUILD_VERSION"
          echo "PYTHON_BUILD_VERSION=$PYTHON_BUILD_VERSION" >> $GITHUB_OUTPUT

      - name: Validate and set PYTHON_PACKAGE_DIST_NAME
        id: validate-package-name
        env:
          PYTHON_PACKAGE_DIST_NAME: ${{ inputs.PYTHON_PACKAGE_DIST_NAME }}
        run: |
          if [[ -z "$PYTHON_PACKAGE_DIST_NAME" ]]; then
            echo "PYTHON_PACKAGE_DIST_NAME is required."
            exit 1
          fi

          echo "Using PYTHON_PACKAGE_DIST_NAME: $PYTHON_PACKAGE_DIST_NAME"
          echo "PYTHON_PACKAGE_DIST_NAME=$PYTHON_PACKAGE_DIST_NAME" >> $GITHUB_OUTPUT
          
  github-release:
    needs: validate-inputs
    name: Sign distribution with Sigstore and Upload to GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.CHECKOUT_SHARED }} # Token with full repo scope.

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ needs.validate-inputs.outputs.PYTHON_BUILD_VERSION }}

      - name: Download Dist
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.validate-inputs.outputs.PYTHON_PACKAGE_DIST_NAME }}
          path: ${{ needs.validate-inputs.outputs.DIST_DIR }}

      - name: Sign Dist with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: >-
            ./${{ needs.validate-inputs.outputs.DIST_DIR }}/*.tar.gz
            ./${{ needs.validate-inputs.outputs.DIST_DIR }}/*.whl

      - name: Get Version from Dist
        id: extract_version
        run: |
          pip install pkginfo -c shared/constraints.txt
          
          tarball=$(ls ${{ needs.validate-inputs.outputs.DIST_DIR }}/*.tar.gz | head -n 1)
          wheel=$(ls ${{ needs.validate-inputs.outputs.DIST_DIR }}/*.whl | head -n 1)

          if [ -f "$tarball" ]; then
            version=$(python -c "import pkginfo; info = pkginfo.get_metadata('$tarball'); print(info.version)")
          elif [ -f "$wheel" ]; then
            version=$(python -c "import pkginfo; info = pkginfo.get_metadata('$wheel'); print(info.version)")
          else
            echo "No distribution files found."
            exit 1
          fi

          echo "VERSION_TAG=v$version" >> $GITHUB_ENV

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          '${{ env.VERSION_TAG }}'
          --repo '${{ github.repository }}'
          --notes ""

      - name: Upload Artifact Signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release upload
          '${{ env.VERSION_TAG }}' ${{ needs.validate-inputs.outputs.DIST_DIR }}/**
          --repo '${{ github.repository }}'